version: "3.8"

services:
  mongodb:
    image: arm64v8/mongo:5.0
    platform: linux/arm64/v8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nestjs:
    image: node:20
    container_name: nestjs
    working_dir: /app
    volumes:
      - ./hadopiw-back:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  vuejs:
    image: node:20
    container_name: vuejs
    working_dir: /app
    volumes:
      - ./hadopiw-front:/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"

volumes:
  mongo-data:
